
CREATE TABLE [dbo].[Buyer]
(
    ID			INT IDENTITY (1,1) NOT NULL,
    Name		NVARCHAR(100) NOT NULL,

    CONSTRAINT [PK_dbo.Buyer] PRIMARY KEY CLUSTERED (ID)
);

CREATE TABLE [dbo].[Seller]
(
    ID			INT IDENTITY (1,1) NOT NULL,
    Name		NVARCHAR(100) NOT NULL,

    CONSTRAINT [PK_dbo.Seller] PRIMARY KEY CLUSTERED (ID)
);

CREATE TABLE [dbo].[Item]
(
    ID			INT IDENTITY (1,1) NOT NULL,
    Name		NVARCHAR(100) NOT NULL,
	Description	NVARCHAR(500) NOT NULL,
	SellerID	INT NOT NULL,

    CONSTRAINT [PK_dbo.Buyer] PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT [FK_dbo.Buyer] FOREIGN KEY (SellerID) REFERENCES [dbo].[Seller] (ID)
);

CREATE TABLE [dbo].[Bid]
(
    ID			INT IDENTITY (1,1) NOT NULL,
    BuyerID		NVARCHAR(100) NOT NULL,
	ItemID		NVARCHAR(500) NOT NULL,
	Timestamp	DATETIME NOT NULL,
	Price		FLOAT NOT NULL,

    CONSTRAINT [PK_dbo.Bid] PRIMARY KEY CLUSTERED (ID),
	CONSTRAINT [FK_dbo.Bid] FOREIGN KEY (BuyerID) REFERENCES [dbo].[Buyer] (ID),
	CONSTRAINT [FK_dbo.Bid] FOREIGN KEY (ItemID) REFERENCES [dbo].[Item] (ID)
);